version: '3.8'

services:
  web:
    build: ./assignment1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./assignment1/:/usr/src/assignment1/
    ports:
      - 8000:8000

    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=My1DB2Pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

volumes:
  postgres_data: