version: '3.8'

services:
  web:
    build:
      context: ./assignment1
      dockerfile: Dockerfile.prod
    command: gunicorn assignment1.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=My1DB2Pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: