# Generated by Django 4.1.7 on 2023-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('income', models.IntegerField(max_length=7)),
                ('email', models.EmailField(max_length=75)),
                ('age', models.IntegerField(max_length=4)),
            ],
        ),
    ]
