# Generated by Django 4.1.7 on 2023-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='income',
            field=models.IntegerField(),
        ),
    ]
