# Generated by Django 4.1.7 on 2023-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0003_location_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='county',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
