# Generated by Django 4.1.7 on 2023-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0005_alter_company_hq_location_alter_location_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hq_location',
        ),
        migrations.AddField(
            model_name='company',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a1_api.company'),
        ),
    ]
