# Generated by Django 4.1.7 on 2023-03-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0006_remove_company_hq_location_company_start_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_ids', to='a1_api.company'),
        ),
        migrations.CreateModel(
            name='PersonWorkingAtCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1_api.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1_api.person')),
            ],
        ),
    ]
