# Generated by Django 4.1.7 on 2023-03-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0007_alter_location_company_personworkingatcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_ids', related_query_name='location_id', to='a1_api.company'),
        ),
        migrations.AlterField(
            model_name='personworkingatcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_working_here', to='a1_api.company'),
        ),
        migrations.AlterField(
            model_name='personworkingatcompany',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_at_companies', to='a1_api.person'),
        ),
    ]
