# Generated by Django 4.1.7 on 2023-03-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0008_alter_location_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='income',
            new_name='worker_id',
        ),
    ]
