# Generated by Django 4.1.7 on 2023-03-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0009_rename_income_person_worker_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personworkingatcompany',
            unique_together={('person', 'company')},
        ),
    ]
