# Generated by Django 4.1.7 on 2023-03-27 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0010_alter_personworkingatcompany_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=75, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='personworkingatcompany',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
