# Generated by Django 4.1.7 on 2023-04-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0011_alter_company_start_year_alter_location_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='county',
        ),
        migrations.AlterField(
            model_name='location',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='a1_api.company'),
        ),
    ]
