# Generated by Django 4.1.7 on 2023-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0014_personworkingatcompany_ind_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_company',
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['company'], include=('salary',), name='ind_company'),
        ),
    ]
