# Generated by Django 4.1.7 on 2023-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0015_remove_personworkingatcompany_ind_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
