# Generated by Django 4.1.7 on 2023-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0016_location_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], include=('id',), name='ind_company_name_auto'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], include=('id',), name='ind_person_name_auto'),
        ),
    ]
