# Generated by Django 4.1.7 on 2023-04-19 20:09

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0017_company_ind_company_name_auto_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='ind_person_name_auto',
        )
    ]
