# Generated by Django 4.1.7 on 2023-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0019_remove_personworkingatcompany_ind_company'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['company'], include=('salary',), name='ind_company'),
        ),
    ]
