# Generated by Django 4.1.7 on 2023-04-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0020_personworkingatcompany_ind_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_name_auto',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='ind_person_name_auto',
        ),
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_company',
        ),
        migrations.AlterUniqueTogether(
            name='personworkingatcompany',
            unique_together=set(),
        ),
    ]
