# Generated by Django 4.1.7 on 2023-04-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0021_remove_company_ind_company_name_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avg_salary',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
