# Generated by Django 4.1.7 on 2023-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0024_alter_company_name_alter_person_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_name_auto',
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'id'], name='ind_company_name_auto'),
        ),
    ]
