# Generated by Django 4.1.7 on 2023-04-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0026_remove_person_ind_person_name_auto_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='ind_comp_avg_salary',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_name_auto',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_reputation',
        ),
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_company',
        ),
        migrations.AlterUniqueTogether(
            name='personworkingatcompany',
            unique_together=set(),
        ),
    ]
