# Generated by Django 4.1.7 on 2023-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0029_company_nr_locations_company_ind_nr_locations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_company',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='ind_company_avg_salary',
            old_name='ind_comp_avg_salary',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='ind_company_nr_locations',
            old_name='ind_nr_locations',
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company', 'id'], name='ind_pc_location'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['company', 'id'], include=('salary',), name='ind_pc_company'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['person', 'id'], include=('salary',), name='ind_pc_person'),
        ),
    ]
