# Generated by Django 4.1.7 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0030_remove_personworkingatcompany_ind_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('bio', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('high_school', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('university', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
