# Generated by Django 4.1.7 on 2023-05-04 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0034_personworkingatcompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reputation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'id'], name='ind_company_user'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'id'], name='ind_person_user'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['user', 'id'], name='ind_pc_user'),
        ),
    ]
