# Generated by Django 4.1.7 on 2023-05-04 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0035_alter_company_reputation_company_ind_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_salary',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='net_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='worker_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
