# Generated by Django 4.1.7 on 2023-05-06 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0037_userprofile_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='apartment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.RegexValidator('^(?!.*[#$%^&*!]).*$', 'Special characters (#,$,%,^,&,*,!) not permitted.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='high_school',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator('^(?!.*[#$%^&*!]).*$', 'Special characters (#,$,%,^,&,*,!) not permitted.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=70, validators=[django.core.validators.RegexValidator('^(?!.*[#$%^&*!]).*$', 'Special characters (#,$,%,^,&,*,!) not permitted.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator('^(?!.*[#$%^&*!]).*$', 'Special characters (#,$,%,^,&,*,!) not permitted.')]),
        ),
    ]
