# Generated by Django 4.1.7 on 2023-05-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0038_userprofile_role_alter_location_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_name_auto',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_avg_salary',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_reputation',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_nr_locations',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='ind_company_user',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='ind_pc_location',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='ind_person_user',
        ),
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_pc_company',
        ),
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_pc_person',
        ),
        migrations.RemoveIndex(
            model_name='personworkingatcompany',
            name='ind_pc_user',
        ),
        migrations.AlterUniqueTogether(
            name='personworkingatcompany',
            unique_together=set(),
        ),
    ]
