# Generated by Django 4.1.7 on 2023-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0039_remove_company_ind_company_name_auto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personworkingatcompany',
            unique_together={('person', 'company')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'id'], name='ind_company_name_auto'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['avg_salary', 'id'], name='ind_company_avg_salary'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['reputation', 'id'], name='ind_company_reputation'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['nr_locations', 'id'], name='ind_company_nr_locations'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'id'], name='ind_company_user'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company', 'id'], name='ind_pc_location'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'id'], name='ind_person_user'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['company', 'id'], include=('salary',), name='ind_pc_company'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['person', 'id'], include=('salary',), name='ind_pc_person'),
        ),
        migrations.AddIndex(
            model_name='personworkingatcompany',
            index=models.Index(fields=['user', 'id'], name='ind_pc_user'),
        ),
    ]
