# Generated by Django 4.1.7 on 2023-06-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1_api', '0043_remove_message_user_message_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='nickname',
        ),
    ]
